name: Build and Push Docker Image to JFrog
on: 
    push:
        branches:
            -   main
    workflow_dispatch:
jobs:

    build:
        runs-on: node-latest

        steps:
            -   name: checkout code
                uses: actions/checkout@v3
            -   name: set up Docker Buuildx
                uses: docker/setup-buildx-action@v2
            -   name: Build Docker Image
                run: docker build -t myapp  
